
[package]
name = "bitrust_bencode"
description = "Bencode serialization format"
version = "0.1.0"
authors = ["Adrian Plavka <adrian.plavka@gmail.com>"]
repository = "https://github.com/adrianplavka/bitrust/tree/master/bencode"
keywords = ["bencode", "serde", "serialization"]
categories = ["encoding"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE.md"]
license = "MIT"
edition = "2018"

[dependencies]
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
